'use client'

import { useState } from 'react'
import Link from 'next/link'
import Navbar, { type Language } from '@/components/Navbar'

const labels = {
  EN: {
    back: '← Home',
    tagline: 'AI-powered FIFA World Cup 2026 predictions',
    about: 'About',
    whatTitle: 'What is Innovera Predictor?',
    whatBody:
      'Innovera World Cup AI Predictor is an AI-powered platform that provides real-time FIFA World Cup 2026 match predictions, luck scores, team momentum analytics, and SHAP-based explainability for every match in the tournament.',
    howTitle: 'How does it work?',
    howBody:
      'Our prediction engine is trained on historical match data, squad strength, recent form, head-to-head records, and contextual factors. For each match, we generate win/draw/loss probabilities alongside a SHAP breakdown explaining the four most influential factors. After each match, we compute a luck score (–10 to +10) measuring how much a team over- or under-performed relative to their expected output.',
    techTitle: 'Technology',
    techBody:
      'The backend runs on a FastAPI service hosted on Hugging Face Spaces. Match and prediction data are stored in Supabase (PostgreSQL). The frontend is built with Next.js 14, TypeScript, and Tailwind CSS.',
    disclaimerTitle: 'Disclaimer',
    disclaimerBody:
      'Innovera Predictor is for entertainment and educational purposes only. Predictions are generated by AI models and do not constitute betting advice. All football data belongs to FIFA and respective rights holders.',
    googleNote: 'Google Sign-In',
    googleBody:
      'When signing in with Google, you will see "Innovera AI Predictor" on the consent screen. This is the shortened name used due to Google\'s character limit — it refers to the same app.',
    features: [
      { icon: '🤖', title: 'AI Match Predictions', desc: 'Win / draw / loss probabilities for every match.' },
      { icon: '📊', title: 'SHAP Explainability', desc: 'Understand why the model made each prediction.' },
      { icon: '🍀', title: 'Luck Scores', desc: 'Measure how lucky or unlucky each team was post-match.' },
      { icon: '📈', title: 'Momentum Tracker', desc: 'Real-time Rising / Falling / Stable team form.' },
      { icon: '🏆', title: 'Group Standings', desc: 'Live standings across all 12 WC 2026 groups.' },
      { icon: '🌐', title: 'Bilingual', desc: 'Full English and Kurdish (Sorani) support.' },
    ],
    contact: 'Contact',
    contactBody: 'For inquiries contact us at',
  },
  KU: {
    back: '← سەرەکی',
    tagline: 'پێشبینی جامی جیهان ٢٠٢٦ بە هوشی دەستکرد',
    about: 'دەربارە',
    whatTitle: 'ئینۆڤێرا پێشبینیکەر چییە؟',
    whatBody:
      'ئینۆڤێرا — پێشبینیکەری زیرەکی دەستکردی جامی جیهانی پلاتفۆرمێکی هوشی دەستکردە کە پێشبینیی یارییەکانی جامی جیهانی FIFA ٢٠٢٦ بەکردەوە دەدات، لەگەڵ خەمەی بەخت، ئەنالیزی مۆمێنتەمی تیم، و ڕوونکردنەوەی SHAP بۆ هەر یارییەک.',
    howTitle: 'چۆن کاردەکات؟',
    howBody:
      'ئامرازی پێشبینیمان لەسەر داتای مێژووی یاری، توانای دەستە، فۆڕمی دوایین، ناسنامەی سەر بەسەر، و هۆکارە پەیوەندیدارەکان ماشین-فێربووە. بۆ هەر یارییەک ئاگادارکردنەوەی بردنەوە/یەکسان/دژێ درووست دەکەین لەگەڵ ڕوونکردنەوەی SHAP.',
    techTitle: 'تەکنەلۆجیا',
    techBody:
      'بەکەند FastAPI لەسەر Hugging Face Spaces کار دەکات. داتای یاری و پێشبینی لە Supabase (PostgreSQL) پاراستراوە. پەڕەی پێشەوەی Next.js 14، TypeScript، و Tailwind CSS بەکاردێت.',
    disclaimerTitle: 'ئاگادارکردنەوە',
    disclaimerBody:
      'ئینۆڤێرا پێشبینیکەر تەنها بۆ مەرجی مایەدانی و پەروەردەیییە. پێشبینیەکان بە هوشی دەستکرد درووستکراون و ئەمە بریتی نیە لە ئامۆژگاری مەرجبازی. هەموو داتای تۆپی پێ گیرا FIFA و خاوەن مافەکانی پەیوەندیدارەکانیانە.',
    googleNote: 'چوونەژوورەوەی Google',
    googleBody:
      'کاتێک بە Google دەچیتە ژوورەوە، "Innovera AI Predictor" لەسەر پەڕەی ڕازیبوون دەبینیت. ئەمە ناوی کورتکراوەیە بەهۆی سنووری پیتی Google — هەمان ئەپی فەرمییە.',
    features: [
      { icon: '🤖', title: 'پێشبینی یاری بە AI', desc: 'پێشبینی بردنەوە/یەکسان/دژێ بۆ هەر یارییەک.' },
      { icon: '📊', title: 'ڕوونکردنەوەی SHAP', desc: 'تێبگە بۆچی مۆدێل ئەم پێشبینیە دروستی کردووە.' },
      { icon: '🍀', title: 'خەمەکانی بەخت', desc: 'پێوانەی خۆشبەختی یان بەدبەختی تیم دوای یاری.' },
      { icon: '📈', title: 'بەدواداچوونی مۆمێنتەم', desc: 'فۆڕمی تیم بەکردەوە: بەرزبوون/کەمبوون/جێگیر.' },
      { icon: '🏆', title: 'پلەبەندی گروپ', desc: 'پلەبەندی بەکردەوە لە هەموو ١٢ گروپی جامی جیهان ٢٠٢٦.' },
      { icon: '🌐', title: 'دوو زمانە', desc: 'پشتگیری تەواوی زمانی ئینگلیزی و کوردی (سۆرانی).' },
    ],
    contact: 'پەیوەندی',
    contactBody: 'بۆ داواکاری پەیوەندیمان پێوە بکە لە',
  },
}

export default function AboutPage() {
  const [language, setLanguage] = useState<Language>('EN')
  const t = labels[language]

  return (
    <div className="min-h-screen bg-[#0D1117]">
      <Navbar language={language} onLanguageChange={setLanguage} />

      <main className="mx-auto max-w-3xl px-4 sm:px-6 py-12 space-y-12">
        {/* Back */}
        <Link href="/" className="inline-flex items-center gap-1 text-sm text-[#8B949E] hover:text-[#F0A500] transition-colors">
          {t.back}
        </Link>

        {/* ── Hero ─────────────────────────────────────────────────────────── */}
        <div className="flex items-center gap-5">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#F0A500] flex-shrink-0 shadow-xl shadow-[#F0A500]/20">
            <svg viewBox="0 0 24 24" fill="none" className="h-9 w-9" aria-hidden="true">
              <circle cx="12" cy="12" r="10" fill="#0D1117" />
              <path d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2z" stroke="#F0A500" strokeWidth="1.5" />
              <path d="M12 7l1.5 4.5H18l-3.75 2.72 1.43 4.4L12 15.95l-3.68 2.67 1.43-4.4L6 11.5h4.5L12 7z" fill="#F0A500" />
            </svg>
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-[#E6EDF3] leading-tight">
              {language === 'KU'
                ? <><span className="text-[#F0A500]">ئینۆڤێرا</span> — پێشبینیکەری زیرەکی دەستکردی جامی جیهانی</>
                : <>Innovera <span className="text-[#F0A500]">World Cup AI Predictor</span></>
              }
            </h1>
            <p className="mt-1 text-sm text-[#8B949E]">{t.tagline}</p>
            <p className="mt-1 text-[10px] text-[#30363D] tracking-widest font-medium">innovera.ai</p>
          </div>
        </div>

        {/* ── Feature grid ─────────────────────────────────────────────────── */}
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {t.features.map((f) => (
            <div key={f.title} className="bg-[#161B22] border border-[#30363D] rounded-xl p-4 space-y-2">
              <span className="text-2xl">{f.icon}</span>
              <p className="text-sm font-semibold text-[#E6EDF3]">{f.title}</p>
              <p className="text-xs text-[#8B949E] leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>

        {/* ── Content sections ─────────────────────────────────────────────── */}
        {[
          { title: t.whatTitle, body: t.whatBody },
          { title: t.howTitle,  body: t.howBody  },
          { title: t.techTitle, body: t.techBody  },
        ].map(({ title, body }) => (
          <section key={title} className="space-y-3">
            <h2 className="text-lg font-bold text-[#E6EDF3]">{title}</h2>
            <p className="text-sm text-[#8B949E] leading-relaxed">{body}</p>
          </section>
        ))}

        {/* ── Google consent note ────────────────────────────────────��─────── */}
        <section className="bg-[#161B22] border border-[#30363D] rounded-xl p-5 space-y-3">
          <div className="flex items-center gap-3">
            {/* Google "G" icon (no external URL — inline SVG) */}
            <svg viewBox="0 0 24 24" className="h-6 w-6 flex-shrink-0" aria-hidden="true">
              <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
              <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
              <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
              <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
            </svg>
            <h3 className="text-sm font-semibold text-[#E6EDF3]">{t.googleNote}</h3>
          </div>
          <p className="text-sm text-[#8B949E] leading-relaxed">{t.googleBody}</p>
          <div className="bg-[#0D1117] border border-[#30363D] rounded-lg px-4 py-3">
            <p className="text-xs text-[#8B949E]">
              {language === 'KU' ? 'ناوی ئەپ لەسەر پەڕەی Google:' : 'App name shown on Google consent screen:'}
            </p>
            <p className="text-sm font-bold text-[#E6EDF3] mt-0.5">Innovera AI Predictor</p>
            <p className="text-[10px] text-[#8B949E] mt-0.5">
              {language === 'KU'
                ? '(ناوی کورتکراو بۆ سنووری Google — هەمان ئەپی "Innovera World Cup AI Predictor"یە)'
                : '(Shortened for Google\'s character limit — same app as "Innovera World Cup AI Predictor")'}
            </p>
          </div>
        </section>

        {/* ── Disclaimer ───────────────────────────────────────────────────── */}
        <section className="bg-[#F85149]/5 border border-[#F85149]/20 rounded-xl p-5 space-y-2">
          <h3 className="text-sm font-bold text-[#F85149]">{t.disclaimerTitle}</h3>
          <p className="text-xs text-[#8B949E] leading-relaxed">{t.disclaimerBody}</p>
        </section>

        {/* ── Contact ──────────────────────────────────────────────────────── */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-[#E6EDF3]">{t.contact}</h2>
          <p className="text-sm text-[#8B949E]">
            {t.contactBody}{' '}
            <a
              href="mailto:hello@innovera.ai"
              className="text-[#F0A500] hover:underline font-medium"
            >
              hello@innovera.ai
            </a>
          </p>
        </section>

        {/* ── Footer stamp ─────────────────────────────────────────────────── */}
        <div className="border-t border-[#30363D] pt-8 flex items-center justify-between">
          <p className="text-xs text-[#30363D] tracking-widest font-medium">innovera.ai</p>
          <p className="text-xs text-[#8B949E]">
            {language === 'KU' ? '© ٢٠٢٦ Innovera' : '© 2026 Innovera · All rights reserved'}
          </p>
        </div>
      </main>
    </div>
  )
}
