'use client'

import Link from 'next/link'
import Navbar from '@/components/Navbar'
import { useLanguage } from '@/hooks/useLanguage'

const labels = {
  EN: {
    back: '← Home',
    tagline: 'AI-powered Premier League 2026-27 predictions',
    about: 'About',

    // Mission
    missionTitle: 'Our Mission',
    missionBody:
      'Ennovera is an AI research team building sports intelligence tools. Our goal is to make high-quality match analysis accessible to everyone — breaking down complex data into clear, explainable predictions. Ennovera is our flagship product, currently covering the Premier League 2026-27 season.',

    // How AI works
    howTitle: 'How the AI Works',
    steps: [
      {
        num: '01',
        title: 'Data Collection',
        desc: 'We ingest historical match data, squad ratings, recent form, head-to-head records, venue data, and tournament context from StatsBomb, FBref, and API-Football.',
      },
      {
        num: '02',
        title: 'Model Training',
        desc: 'An XGBoost ensemble is trained on thousands of international matches. SHAP (SHapley Additive exPlanations) is used to make each prediction fully transparent.',
      },
      {
        num: '03',
        title: 'Live Predictions',
        desc: 'For each match we output win/draw/loss probabilities, the 4 most influential SHAP factors, most likely scorelines, team momentum, and a post-match luck score (−10 to +10).',
      },
    ],

    // Data sources
    sourcesTitle: 'Data Sources',
    sources: [
      { name: 'StatsBomb', desc: 'Event-level match data & squad metrics', icon: '📊' },
      { name: 'FBref', desc: 'Historical stats, xG, and team form', icon: '📈' },
      { name: 'API-Football', desc: 'Live scores, fixtures, and standings', icon: '⚡' },
    ],

    // Features
    features: [
      { icon: '🤖', title: 'AI Match Predictions', desc: 'Win / draw / loss probabilities for every match.' },
      { icon: '📊', title: 'SHAP Explainability', desc: 'Understand why the model made each prediction.' },
      { icon: '🍀', title: 'Luck Scores', desc: 'Measure how lucky or unlucky each team was post-match.' },
      { icon: '📈', title: 'Momentum Tracker', desc: 'Real-time Rising / Falling / Stable team form.' },
      { icon: '🌐', title: 'Bilingual', desc: 'Full English and Kurdish (Sorani) support.' },
    ],

    // Tech
    techTitle: 'Technology',
    techBody:
      'The backend runs on a FastAPI service hosted on Hugging Face Spaces. Match and prediction data are stored in Supabase (PostgreSQL). The frontend is built with Next.js 14, TypeScript, and Tailwind CSS. Auth via Supabase OAuth (Google, Facebook).',

    // Contact
    contact: 'Contact',
    contactBody: 'For inquiries contact us at',

    // Google consent
    googleNote: 'Google Sign-In',
    googleBody:
      "When signing in with Google, you will see \"Ennovera AI Predictor\" on the consent screen. This is the shortened name used due to Google's character limit — it refers to the same app.",

    // Disclaimer
    disclaimerTitle: 'Disclaimer',
    disclaimerBody:
      'Ennovera is for entertainment and educational purposes only. Predictions are generated by AI models and do not constitute betting advice. All football data belongs to the Premier League and respective rights holders.',

    // Badge
    builtWith: 'Built with',
    claudeCode: 'Claude Code',
  },
  KU: {
    back: '← سەرەکی',
    tagline: 'پێشبینی پرێمیەر لیگ ٢٠٢٦-٢٧ بە زیرەکی دەستکرد',
    about: 'دەربارە',

    missionTitle: 'ئامانجی ئێمە',
    missionBody:
      'ئینۆڤێرا تیمێکی توێژینەوەی هوشی دەستکردە کە ئامرازی زیرەکی وەرزشی دروست دەکات. ئامانجمان ئەوەیە کە شیکاری یاریی باش بۆ هەمیشکێک بەردەست بکەین — داتای ئاستەواز بکرێت بۆ پێشبینیی ڕوون و ڕوونکراوەوە. ئینۆڤێرا بەرهەمی سەرەکیمانە، ئێستا بۆ وەرزی پرێمیەر لیگ ٢٠٢٦-٢٧.',

    howTitle: '‏AI چۆن کاردەکات',
    steps: [
      {
        num: '٠١',
        title: 'کۆکردنەوەی داتا',
        desc: 'داتای مێژووی یاری، هەرزەی دەستە، فۆڕمی دوایین، ناسنامەی سەر بەسەر، داتای شوێن، و پەیوەندییەکانی تورنووان لە StatsBomb، FBref، و API-Football وەردەگرین.',
      },
      {
        num: '٠٢',
        title: 'ماشین فێربوون',
        desc: 'XGBoost Ensemble لەسەر هەزاران یارییی نێودەوڵەتی فێرکراوە. SHAP بەکاردێت بۆ ئەوەی هەر پێشبینییەک تەواو ڕوون بێت.',
      },
      {
        num: '٠٣',
        title: 'پێشبینیی بەکردەوە',
        desc: 'بۆ هەر یارییەک پێشبینی بردنەوە/یەکسان/دژێ، ٤ هۆکاری گرنگی SHAP، ئەنجامە پێشبینیکراوەکان، مۆمێنتەمی تیم، و خەمەی بەخت دوای یاری دەدرێت.',
      },
    ],

    sourcesTitle: 'سەرچاوەکانی داتا',
    sources: [
      { name: 'StatsBomb', desc: 'داتای بۆیەکی یاری و مەتریکی دەستە', icon: '📊' },
      { name: 'FBref', desc: 'ئامارەکانی مێژووی، xG، و فۆڕمی تیم', icon: '📈' },
      { name: 'API-Football', desc: 'خاڵی بەکردەوە، بەرنامەکان، و پلەبەندی', icon: '⚡' },
    ],

    features: [
      { icon: '🤖', title: 'پێشبینی یاری بە AI', desc: 'پێشبینی بردنەوە/یەکسان/دژێ بۆ هەر یارییەک.' },
      { icon: '📊', title: 'ڕوونکردنەوەی SHAP', desc: 'تێبگە بۆچی مۆدێل ئەم پێشبینیە دروستی کردووە.' },
      { icon: '🍀', title: 'خەمەکانی بەخت', desc: 'پێوانەی خۆشبەختی یان بەدبەختی تیم دوای یاری.' },
      { icon: '📈', title: 'بەدواداچوونی مۆمێنتەم', desc: 'فۆڕمی تیم بەکردەوە: بەرزبوون/کەمبوون/جێگیر.' },
      { icon: '🌐', title: 'دوو زمانە', desc: 'پشتگیری تەواوی زمانی ئینگلیزی و کوردی (سۆرانی).' },
    ],

    techTitle: 'تەکنەلۆجیا',
    techBody:
      'بەکەند FastAPI لەسەر Hugging Face Spaces کار دەکات. داتای یاری و پێشبینی لە Supabase (PostgreSQL) پاراستراوە. پەڕەی پێشەوە Next.js 14، TypeScript، و Tailwind CSS بەکاردێت. چوونەژوورەوە بە Supabase OAuth (Google، Facebook).',

    contact: 'پەیوەندی',
    contactBody: 'بۆ داواکاری پەیوەندیمان پێوە بکە لە',

    googleNote: 'چوونەژوورەوەی Google',
    googleBody:
      'کاتێک بە Google دەچیتە ژوورەوە، "Ennovera AI Predictor" لەسەر پەڕەی ڕازیبوون دەبینیت. ئەمە ناوی کورتکراوەیە بەهۆی سنووری پیتی Google — هەمان ئەپی فەرمییە.',

    disclaimerTitle: 'ئاگادارکردنەوە',
    disclaimerBody:
      'ئینۆڤێرا تەنها بۆ مەرجی مایەدانی و پەروەردەیییە. پێشبینیەکان زیرەکی دەستکرد درووستکراون و ئەمە بریتی نیە لە ئامۆژگاری مەرجبازی. هەموو داتای تۆپی پێ گیرا پرێمیەر لیگ و خاوەن مافەکانی پەیوەندیدارەکانیانە.',

    builtWith: 'دروستکراوە بە',
    claudeCode: 'Claude Code',
  },
}

export default function AboutPage() {
  const { language, changeLanguage } = useLanguage()
  const t = labels[language]

  return (
    <div className="min-h-screen bg-[#0D1117]">
      <Navbar language={language} onLanguageChange={changeLanguage} />

      <main className="mx-auto max-w-3xl px-4 sm:px-6 py-12 space-y-14">
        {/* Back */}
        <Link href="/" className="inline-flex items-center gap-1 text-sm text-[#8B949E] hover:text-[#F0A500] transition-colors">
          {t.back}
        </Link>

        {/* ── Hero ─────────────────────────────────────────────────────────── */}
        <div className="flex items-center gap-5">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#F0A500] flex-shrink-0 shadow-xl shadow-[#F0A500]/20">
            <svg viewBox="0 0 24 24" fill="none" className="h-9 w-9" aria-hidden="true">
              <circle cx="12" cy="12" r="10" fill="#0D1117" />
              <path d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2z" stroke="#F0A500" strokeWidth="1.5" />
              <path d="M12 7l1.5 4.5H18l-3.75 2.72 1.43 4.4L12 15.95l-3.68 2.67 1.43-4.4L6 11.5h4.5L12 7z" fill="#F0A500" />
            </svg>
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-[#E6EDF3] leading-tight">
              {language === 'KU'
                ? <><span className="text-[#F0A500]">ئینۆڤێرا</span> — پێشبینیکەری زیرەکی دەستکردی پرێمیەر لیگ</>
                : <>Ennovera <span className="text-[#F0A500]">AI</span></>
              }
            </h1>
            <p className="mt-1 text-sm text-[#8B949E]">{t.tagline}</p>
            <p className="mt-1 text-[10px] text-[#30363D] tracking-widest font-medium">Ennovera</p>
          </div>
        </div>

        {/* ── Mission ──────────────────────────────────────────────────────── */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-[#E6EDF3]">{t.missionTitle}</h2>
          <p className="text-sm text-[#8B949E] leading-relaxed">{t.missionBody}</p>
        </section>

        {/* ── How AI works — 3-step visual ─────────────────────────────────── */}
        <section className="space-y-5">
          <h2 className="text-lg font-bold text-[#E6EDF3]">{t.howTitle}</h2>
          <div className="space-y-3">
            {t.steps.map((step, idx) => (
              <div key={idx} className="flex gap-4 bg-[#161B22] border border-[#30363D] rounded-xl p-4">
                <div className="flex-shrink-0 flex h-10 w-10 items-center justify-center rounded-xl bg-[#F0A500]/10 border border-[#F0A500]/30">
                  <span className="text-xs font-extrabold text-[#F0A500] tabular-nums">{step.num}</span>
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-bold text-[#E6EDF3]">{step.title}</p>
                  <p className="text-xs text-[#8B949E] leading-relaxed">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── Data sources ─────────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-lg font-bold text-[#E6EDF3]">{t.sourcesTitle}</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {t.sources.map((src) => (
              <div key={src.name} className="bg-[#161B22] border border-[#30363D] rounded-xl p-4 space-y-2">
                <span className="text-2xl">{src.icon}</span>
                <p className="text-sm font-bold text-[#E6EDF3]">{src.name}</p>
                <p className="text-xs text-[#8B949E] leading-relaxed">{src.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── Feature grid ─────────────────────────────────────────────────── */}
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {t.features.map((f) => (
            <div key={f.title} className="bg-[#161B22] border border-[#30363D] rounded-xl p-4 space-y-2">
              <span className="text-2xl">{f.icon}</span>
              <p className="text-sm font-semibold text-[#E6EDF3]">{f.title}</p>
              <p className="text-xs text-[#8B949E] leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>

        {/* ── Technology ───────────────────────────────────────────────────── */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-[#E6EDF3]">{t.techTitle}</h2>
          <p className="text-sm text-[#8B949E] leading-relaxed">{t.techBody}</p>
        </section>

        {/* ── Google consent note ───────────────────────────────────────────── */}
        <section className="bg-[#161B22] border border-[#30363D] rounded-xl p-5 space-y-3">
          <div className="flex items-center gap-3">
            <svg viewBox="0 0 24 24" className="h-6 w-6 flex-shrink-0" aria-hidden="true">
              <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4" />
              <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853" />
              <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05" />
              <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335" />
            </svg>
            <h3 className="text-sm font-semibold text-[#E6EDF3]">{t.googleNote}</h3>
          </div>
          <p className="text-sm text-[#8B949E] leading-relaxed">{t.googleBody}</p>
          <div className="bg-[#0D1117] border border-[#30363D] rounded-lg px-4 py-3">
            <p className="text-xs text-[#8B949E]">
              {language === 'KU' ? 'ناوی ئەپ لەسەر پەڕەی Google:' : 'App name shown on Google consent screen:'}
            </p>
            <p className="text-sm font-bold text-[#E6EDF3] mt-0.5">Ennovera AI Predictor</p>
            <p className="text-[10px] text-[#8B949E] mt-0.5">
              {language === 'KU'
                ? '(ناوی کورتکراو بۆ سنووری Google — هەمان ئەپی "Ennovera World Cup AI Predictor"یە)'
                : '(Shortened for Google\'s character limit — same app as "Ennovera World Cup AI Predictor")'}
            </p>
          </div>
        </section>

        {/* ── Disclaimer ───────────────────────────────────────────────────── */}
        <section className="bg-[#F85149]/5 border border-[#F85149]/20 rounded-xl p-5 space-y-2">
          <h3 className="text-sm font-bold text-[#F85149]">{t.disclaimerTitle}</h3>
          <p className="text-xs text-[#8B949E] leading-relaxed">{t.disclaimerBody}</p>
        </section>

        {/* ── Contact ──────────────────────────────────────────────────────── */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-[#E6EDF3]">{t.contact}</h2>
          <p className="text-sm text-[#8B949E]">
            {t.contactBody}{' '}
            <a href="mailto:hello@innovera.ai" className="text-[#F0A500] hover:underline font-medium">
              hello@innovera.ai
            </a>
          </p>
          {/* Social placeholders */}
          <div className="flex items-center gap-3 pt-1">
            <a
              href="#"
              aria-label="Twitter / X"
              className="flex items-center justify-center h-9 w-9 rounded-lg bg-[#161B22] border border-[#30363D] text-[#8B949E] hover:text-[#E6EDF3] hover:border-[#58A6FF]/50 transition-all"
            >
              <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4" aria-hidden="true">
                <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
              </svg>
            </a>
            <a
              href="#"
              aria-label="GitHub"
              className="flex items-center justify-center h-9 w-9 rounded-lg bg-[#161B22] border border-[#30363D] text-[#8B949E] hover:text-[#E6EDF3] hover:border-[#8B949E]/50 transition-all"
            >
              <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4" aria-hidden="true">
                <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
              </svg>
            </a>
          </div>
        </section>

        {/* ── Built with Claude Code badge ─────────────────────────────────── */}
        <div className="flex justify-center">
          <a
            href="https://claude.ai/code"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2.5 bg-[#161B22] border border-[#30363D] hover:border-[#F0A500]/40 rounded-full px-5 py-2.5 transition-all group"
          >
            {/* Anthropic mark */}
            <svg viewBox="0 0 16 16" fill="none" className="h-4 w-4 flex-shrink-0" aria-hidden="true">
              <rect width="16" height="16" rx="3" fill="#D4570A" />
              <path d="M8 3.5L11.5 12.5H10L9 10H7L6 12.5H4.5L8 3.5ZM8 6.5L7.5 8.5H8.5L8 6.5Z" fill="white" />
            </svg>
            <span className="text-sm text-[#8B949E] group-hover:text-[#E6EDF3] transition-colors">
              {t.builtWith}{' '}
              <span className="font-bold text-[#F0A500]">{t.claudeCode}</span>
            </span>
          </a>
        </div>

        {/* ── Footer stamp ─────────────────────────────────────────────────── */}
        <div className="border-t border-[#30363D] pt-8 flex items-center justify-between">
          <a
            href="https://ennovera.com"
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-[#30363D] tracking-widest font-medium hover:text-[#F0A500] transition-colors"
          >
            ennovera.com
          </a>
          <p className="text-xs text-[#8B949E]">
            {language === 'KU' ? '© ٢٠٢٦ Ennovera' : '© 2026 Ennovera · All rights reserved'}
          </p>
        </div>
      </main>
    </div>
  )
}
